'use client';

import {
  AlertTriangle,
  ArrowRight,
  Check,
  CheckCircle2,
  Clipboard,
  Download,
  ExternalLink,
  FileCheck2,
  Info,
  LoaderCircle,
  Printer,
  ShieldAlert,
  Upload,
  XCircle,
} from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useEffect, useMemo, useState } from 'react';

import { useApp } from '@/components/app-provider';
import { ScoreRing } from '@/components/score-ring';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import type { FindingStatus, ScanReport } from '@/lib/types';

const stateLabels: Record<ScanReport['implementationState'], string> = {
  not_detected: 'Not detected',
  source_hint_detected: 'Source hint detected',
  runtime_verified: 'Runtime tools verified',
  journey_tested: 'Journey tested',
  improvement_proven: 'Improvement proven',
};

const statusIcon: Record<FindingStatus, typeof CheckCircle2> = {
  pass: CheckCircle2,
  partial: AlertTriangle,
  fail: XCircle,
  not_observed: Info,
  not_applicable: Info,
};

const statusClass: Record<FindingStatus, string> = {
  pass: 'text-positive',
  partial: 'text-warning',
  fail: 'text-destructive',
  not_observed: 'text-muted-foreground',
  not_applicable: 'text-muted-foreground',
};

function formatTime(iso: string) {
  return new Intl.DateTimeFormat('en', {
    dateStyle: 'medium',
    timeStyle: 'short',
  }).format(new Date(iso));
}

function reportSummary(report: ScanReport) {
  return `${report.normalizedUrl}\nImplementation: ${stateLabels[report.implementationState]}\nBaseline actionability: ${report.baselineActionability.value ?? 'N/A'}/100 (${report.baselineActionability.coverage}% source evidence coverage)\nWebMCP quality: ${report.webmcpQuality ? `${report.webmcpQuality.value ?? 'N/A'}/100 (${report.webmcpQuality.coverage}% imported evidence coverage)` : 'Not enough runtime evidence'}\nTop evidence: ${report.strongestEvidence.join('; ')}\nGenerated by isWebMCP.`;
}

export function ReportView({ scanId }: { scanId: string }) {
  const router = useRouter();
  const { currentReport, setCurrentReport, exportPrepared, prepareExport } =
    useApp();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [manifestText, setManifestText] = useState('');
  const [importLoading, setImportLoading] = useState(false);
  const [importMessage, setImportMessage] = useState<string | null>(null);
  const report = currentReport?.id === scanId ? currentReport : null;

  useEffect(() => {
    if (report) {
      return;
    }
    const cached = sessionStorage.getItem(`iswebmcp:report:${scanId}`);
    if (cached) {
      try {
        const parsed = JSON.parse(cached) as ScanReport;
        queueMicrotask(() => {
          setCurrentReport(parsed);
          setLoading(false);
        });
        return;
      } catch {
        sessionStorage.removeItem(`iswebmcp:report:${scanId}`);
      }
    }
    void fetch(`/api/scans/${encodeURIComponent(scanId)}`, {
      cache: 'no-store',
    })
      .then(async (response) => {
        if (!response.ok)
          throw new Error('This ephemeral scan is unavailable or has expired.');
        return (await response.json()) as ScanReport;
      })
      .then((next) => setCurrentReport(next))
      .catch((reason: unknown) =>
        setError(
          reason instanceof Error
            ? reason.message
            : 'The report could not be loaded.',
        ),
      )
      .finally(() => setLoading(false));
  }, [report, scanId, setCurrentReport]);

  const findingGroups = useMemo(() => {
    if (!report) return [];
    return (['P0', 'P1', 'P2'] as const).map((priority) => ({
      priority,
      findings: report.findings.filter(
        (finding) => finding.priority === priority,
      ),
    }));
  }, [report]);

  const copySummary = async () => {
    if (!report) return;
    await navigator.clipboard.writeText(reportSummary(report));
    setCopied(true);
    setTimeout(() => setCopied(false), 2_000);
  };

  const downloadJson = () => {
    if (!report) return;
    const blob = new Blob([JSON.stringify(report, null, 2)], {
      type: 'application/json',
    });
    const href = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = href;
    anchor.download = `iswebmcp-${report.id}.json`;
    anchor.click();
    URL.revokeObjectURL(href);
  };

  const importManifest = async () => {
    if (!report) return;
    setImportLoading(true);
    setImportMessage(null);
    try {
      const decoded = JSON.parse(manifestText) as unknown;
      const containsTools =
        Array.isArray(decoded) ||
        (decoded && typeof decoded === 'object' && 'tools' in decoded);
      if (!containsTools)
        throw new Error(
          'Paste a JSON array of tools or an object with a tools array.',
        );
      const response = await fetch('/api/imports/tool-manifest', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          scanId: report.id,
          manifest: decoded,
        }),
      });
      const payload = (await response.json()) as
        | ScanReport
        | { error?: { message?: string } };
      if (!response.ok || !('id' in payload)) {
        throw new Error(
          'error' in payload
            ? (payload.error?.message ?? 'The manifest was rejected.')
            : 'The manifest was rejected.',
        );
      }
      setCurrentReport(payload);
      setImportMessage(
        `Created a derived report with ${payload.importedProof?.tools.length ?? 0} summarized contract${payload.importedProof?.tools.length === 1 ? '' : 's'}.`,
      );
      router.replace(`/reports/${payload.id}`);
    } catch (error) {
      setImportMessage(
        error instanceof Error
          ? error.message
          : 'The manifest could not be imported.',
      );
    } finally {
      setImportLoading(false);
    }
  };

  const loadManifestFile = async (file: File | undefined) => {
    if (!file) return;
    if (file.size > 128_000) {
      setImportMessage('The manifest exceeds the 128 KB import limit.');
      return;
    }
    setManifestText(await file.text());
    setImportMessage(
      `Loaded ${file.name}. Review the sanitized JSON before importing.`,
    );
  };

  const loadExampleManifest = () => {
    setManifestText(
      JSON.stringify(
        {
          tools: [
            {
              name: 'search_catalog',
              title: 'Search catalog',
              description:
                'Filter visible catalog items using explicit product constraints.',
              inputSchema: {
                type: 'object',
                properties: { query: { type: 'string' } },
                additionalProperties: false,
              },
              annotations: { readOnlyHint: true, untrustedContentHint: true },
            },
          ],
        },
        null,
        2,
      ),
    );
    setImportMessage(
      'Example loaded. Replace it with your sanitized exported contracts when ready.',
    );
  };

  if (loading && !report) {
    return (
      <main className="mx-auto min-h-[70vh] max-w-7xl px-5 py-16 lg:px-8">
        <output
          className="js-report-loading instrument-card mx-auto flex max-w-lg items-center gap-3 p-6"
          aria-live="polite"
        >
          <LoaderCircle
            className="size-5 animate-spin text-signal-ink"
            aria-hidden="true"
          />
          Loading the evidence ledger…
        </output>
        <noscript>
          <style>{'.js-report-loading{display:none}'}</style>
          <div className="instrument-card mx-auto max-w-lg p-6">
            <h1 className="text-xl font-semibold">
              JavaScript is required to restore this ephemeral report
            </h1>
            <p className="mt-3 text-sm leading-6 text-muted-foreground">
              Quick Scan itself never executes the target page. Enable
              JavaScript for this report viewer, or return to the home page and
              use the server JSON response directly.
            </p>
          </div>
        </noscript>
      </main>
    );
  }

  if (error || !report) {
    return (
      <main className="mx-auto min-h-[70vh] max-w-3xl px-5 py-16 lg:px-8">
        <div className="instrument-card p-8 text-center">
          <ShieldAlert
            className="mx-auto size-8 text-warning"
            aria-hidden="true"
          />
          <h1 className="mt-4 text-2xl font-semibold">Report unavailable</h1>
          <p className="mt-2 text-muted-foreground">
            {error ?? 'This report could not be loaded.'}
          </p>
          <Button
            nativeButton={false}
            className="mt-6"
            render={<Link href="/" />}
          >
            Run a new scan
          </Button>
        </div>
      </main>
    );
  }

  return (
    <main className="report-page min-h-screen bg-background pb-16">
      <section className="report-toolbar sticky top-16 z-20 border-b border-border bg-background/94 backdrop-blur-lg print:static">
        <div
          id="export-controls"
          className="mx-auto flex max-w-7xl scroll-mt-32 flex-col gap-4 px-5 py-4 lg:flex-row lg:items-center lg:justify-between lg:px-8"
        >
          <div className="min-w-0">
            <div className="flex flex-wrap items-center gap-2">
              <span className="status-chip bg-card">
                <span className="size-1.5 rounded-full bg-signal" />{' '}
                {stateLabels[report.implementationState]}
              </span>
              {report.importedProof && (
                <span className="status-chip bg-card">
                  <FileCheck2 className="size-3" aria-hidden="true" /> Imported
                  · not independently verified
                </span>
              )}
              <span className="font-mono text-[10px] uppercase tracking-wider text-muted-foreground">
                Source scan · {formatTime(report.scannedAt)}
              </span>
            </div>
            <h1 className="mt-2 truncate text-lg font-semibold tracking-tight">
              {report.normalizedUrl}
            </h1>
          </div>
          <div className="flex flex-wrap items-center gap-2 print:hidden">
            <Button variant="outline" onClick={copySummary}>
              {copied ? (
                <Check data-icon="inline-start" />
              ) : (
                <Clipboard data-icon="inline-start" />
              )}
              {copied ? 'Copied' : 'Copy summary'}
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                prepareExport('json');
                downloadJson();
              }}
            >
              <Download data-icon="inline-start" /> JSON
            </Button>
            <Button
              variant="outline"
              onClick={() => {
                prepareExport('print');
                setTimeout(() => window.print(), 100);
              }}
            >
              <Printer data-icon="inline-start" /> Print
            </Button>
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-7xl space-y-8 px-5 py-8 lg:px-8">
        {exportPrepared && (
          <output
            className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-positive/25 bg-positive/8 p-4 text-sm print:hidden"
            aria-live="polite"
          >
            <span>
              <CheckCircle2
                className="mr-2 inline size-4 text-positive"
                aria-hidden="true"
              />
              {exportPrepared.format.toUpperCase()} export is ready from the
              visible report controls.
            </span>
            <a
              className="font-semibold underline underline-offset-4"
              href={exportPrepared.href}
            >
              Go to export controls
            </a>
          </output>
        )}

        <section aria-labelledby="measurement-heading">
          <div className="mb-5 flex flex-wrap items-end justify-between gap-3">
            <div>
              <p className="eyebrow">Evidence report</p>
              <h2
                id="measurement-heading"
                className="mt-2 text-3xl font-semibold tracking-[-.04em]"
              >
                Three measurements. No blended score.
              </h2>
            </div>
            <span className="font-mono text-xs text-muted-foreground">
              Report ID {report.id}
            </span>
          </div>
          <div className="grid gap-4 lg:grid-cols-3">
            <ScoreRing
              value={report.baselineActionability.value}
              label="Baseline actionability"
              detail={`${report.baselineActionability.coverage}% evidence coverage. Measures source-visible human UI structure—not WebMCP quality.`}
            />
            <ScoreRing
              value={report.webmcpQuality?.value ?? null}
              label="WebMCP quality"
              detail={
                report.importedProof
                  ? `${report.webmcpQuality?.coverage ?? 0}% imported evidence coverage. Contract audit only—not independently verified runtime behavior.`
                  : 'Not enough runtime evidence. Quick Scan never converts a source hint into a runtime score.'
              }
              tone="neutral"
            />
            <ScoreRing
              value={null}
              label="WebMCP Lift"
              detail="Awaiting a comparable baseline and WebMCP journey in the controlled proof lab."
              tone="muted"
            />
          </div>
        </section>

        <section
          className="instrument-card overflow-hidden"
          aria-labelledby="import-heading"
        >
          <div className="grid gap-6 p-5 sm:p-6 lg:grid-cols-[.72fr_1.28fr]">
            <div>
              <p className="eyebrow">Imported contract evidence</p>
              <h2 id="import-heading" className="mt-2 text-xl font-semibold">
                Audit exported tool contracts
              </h2>
              <p className="mt-3 text-sm leading-6 text-muted-foreground">
                Paste a sanitized export or a canonical same-origin probe
                envelope. Manual imports are bound to this report but remain
                user-supplied; isWebMCP never claims they were observed or
                executed.
              </p>
              <div className="mt-4 rounded-lg border border-warning/25 bg-warning/8 p-3 text-xs leading-5 text-muted-foreground">
                <strong className="text-foreground">
                  Remove secrets and customer data.
                </strong>{' '}
                Tool contracts should never contain credentials.
              </div>
              {report.importedProof && (
                <div className="mt-4 flex items-center gap-2 text-sm font-medium text-positive">
                  <FileCheck2 className="size-4" aria-hidden="true" />{' '}
                  {report.importedProof.tools.length} imported contract
                  {report.importedProof.tools.length === 1 ? '' : 's'} attached
                </div>
              )}
            </div>
            <div>
              <Textarea
                value={manifestText}
                onChange={(event) => setManifestText(event.target.value)}
                rows={9}
                maxLength={128_000}
                spellCheck={false}
                aria-label="Sanitized tool manifest JSON"
                placeholder={
                  '{"tools":[{"name":"search_catalog","description":"..."}]}'
                }
                className="font-mono text-xs"
              />
              <div className="mt-3 flex flex-wrap items-center gap-2">
                <Button
                  onClick={importManifest}
                  disabled={!manifestText.trim() || importLoading}
                >
                  <Upload data-icon="inline-start" />{' '}
                  {importLoading ? 'Validating…' : 'Import and audit'}
                </Button>
                <Button
                  nativeButton={false}
                  variant="outline"
                  render={
                    <label
                      htmlFor="manifest-file"
                      aria-label="Choose JSON file"
                    />
                  }
                >
                  Choose JSON file
                </Button>
                <input
                  id="manifest-file"
                  className="sr-only"
                  tabIndex={-1}
                  aria-hidden="true"
                  type="file"
                  accept="application/json,.json"
                  onChange={(event) =>
                    void loadManifestFile(event.target.files?.[0])
                  }
                />
                <button
                  type="button"
                  className="text-xs font-semibold underline underline-offset-4"
                  onClick={loadExampleManifest}
                >
                  Load example
                </button>
              </div>
              {importMessage && (
                <output
                  className="mt-3 block text-xs leading-5 text-muted-foreground"
                  aria-live="polite"
                >
                  {importMessage}
                </output>
              )}
            </div>
          </div>
        </section>

        <aside
          className="grid gap-4 rounded-xl border border-warning/25 bg-warning/8 p-5 md:grid-cols-[auto_1fr]"
          aria-labelledby="limits-heading"
        >
          <AlertTriangle
            className="mt-0.5 size-5 text-warning"
            aria-hidden="true"
          />
          <div>
            <h2 id="limits-heading" className="font-semibold">
              What this scan cannot establish
            </h2>
            <ul className="mt-2 grid gap-2 text-sm leading-6 text-muted-foreground md:grid-cols-2">
              {report.limitations.map((limitation) => (
                <li key={limitation}>— {limitation}</li>
              ))}
            </ul>
          </div>
        </aside>

        <section
          className="grid gap-5 xl:grid-cols-[.82fr_1.18fr]"
          aria-labelledby="baseline-heading"
        >
          <div className="instrument-card p-5 sm:p-6">
            <p className="eyebrow">Observed source</p>
            <h2 id="baseline-heading" className="mt-2 text-xl font-semibold">
              Baseline categories
            </h2>
            <div className="mt-6 space-y-5">
              {report.baselineActionability.categories.map((category) => (
                <div key={category.id}>
                  <div className="mb-2 flex items-center justify-between gap-3 text-sm">
                    <span className="font-medium">{category.label}</span>
                    <span className="font-mono text-xs text-muted-foreground">
                      {category.score ?? 'N/O'} · {category.weight}% weight
                    </span>
                  </div>
                  <div
                    className="h-1.5 overflow-hidden rounded-full bg-muted"
                    aria-hidden="true"
                  >
                    <span
                      className="block h-full rounded-full bg-signal-ink"
                      style={{ width: `${category.score ?? 0}%` }}
                    />
                  </div>
                  <p className="mt-2 text-xs leading-5 text-muted-foreground">
                    {category.explanation}
                  </p>
                </div>
              ))}
            </div>
          </div>

          <div className="instrument-card p-5 sm:p-6">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="eyebrow">Coverage layers</p>
                <h2 className="mt-2 text-xl font-semibold">
                  Action Surface Map
                </h2>
              </div>
              <span className="status-chip">
                {report.actionSurface.length} candidates
              </span>
            </div>
            {report.actionSurface.length ? (
              <div className="mt-6 overflow-x-auto pb-1">
                <div className="min-w-[440px] space-y-2">
                  <div className="grid grid-cols-[minmax(0,1fr)_72px_72px_84px] gap-2 px-3 font-mono text-[9px] uppercase tracking-wider text-muted-foreground">
                    <span>Action</span>
                    <span>Human UI</span>
                    <span>Agent UI</span>
                    <span>WebMCP</span>
                  </div>
                  {report.actionSurface.map((action) => (
                    <div
                      key={action.id}
                      className="grid grid-cols-[minmax(0,1fr)_72px_72px_84px] items-center gap-2 rounded-lg border border-border bg-card p-3 text-sm"
                    >
                      <div className="min-w-0">
                        <p className="truncate font-medium">{action.name}</p>
                        <p className="truncate text-xs text-muted-foreground">
                          {action.risk.replaceAll('_', ' ')}
                        </p>
                      </div>
                      <span
                        className={`coverage-pill ${action.humanUiAvailable ? 'coverage-yes' : 'coverage-unknown'}`}
                      >
                        {action.humanUiAvailable ? 'Yes' : 'Not seen'}
                      </span>
                      <span className="coverage-pill coverage-inferred">
                        {action.agentUiConfidence}
                      </span>
                      <span
                        className={`coverage-pill ${action.webmcpStatus === 'imported' ? 'coverage-inferred' : action.webmcpStatus === 'verified' ? 'coverage-yes' : 'coverage-unknown'}`}
                      >
                        {action.webmcpStatus === 'imported'
                          ? 'Imported'
                          : action.webmcpStatus === 'verified'
                            ? 'Verified'
                            : action.webmcpStatus === 'withheld'
                              ? 'Withheld'
                              : 'Unknown'}
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="mt-6 rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground">
                No task-oriented source actions were confidently inferred.
              </div>
            )}
          </div>
        </section>

        <section aria-labelledby="findings-heading">
          <div className="mb-5">
            <p className="eyebrow">Prioritized remediation</p>
            <h2
              id="findings-heading"
              className="mt-2 text-2xl font-semibold tracking-tight"
            >
              Findings
            </h2>
          </div>
          <div className="grid gap-4 lg:grid-cols-3">
            {findingGroups.map((group) => (
              <div key={group.priority} className="instrument-card p-5">
                <div className="mb-4 flex items-center justify-between">
                  <span
                    className={`priority-badge priority-${group.priority.toLowerCase()}`}
                  >
                    {group.priority}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {group.findings.length} finding
                    {group.findings.length === 1 ? '' : 's'}
                  </span>
                </div>
                <div className="space-y-3">
                  {group.findings.map((finding) => {
                    const Icon = statusIcon[finding.status];
                    return (
                      <article
                        key={finding.id}
                        className="rounded-lg border border-border bg-card p-4"
                      >
                        <div className="flex gap-2.5">
                          <Icon
                            className={`mt-0.5 size-4 shrink-0 ${statusClass[finding.status]}`}
                            aria-hidden="true"
                          />
                          <div>
                            <h3 className="text-sm font-semibold">
                              {finding.title}
                            </h3>
                            <p className="mt-2 text-xs leading-5 text-muted-foreground">
                              {finding.recommendation}
                            </p>
                            <span className="mt-3 inline-block font-mono text-[9px] uppercase tracking-wider text-muted-foreground">
                              {finding.status.replaceAll('_', ' ')}
                            </span>
                          </div>
                        </div>
                      </article>
                    );
                  })}
                </div>
              </div>
            ))}
          </div>
        </section>

        <section
          className="instrument-card overflow-hidden"
          aria-labelledby="evidence-heading"
        >
          <div className="border-b border-border p-5 sm:p-6">
            <p className="eyebrow">Inspectable proof</p>
            <h2 id="evidence-heading" className="mt-2 text-xl font-semibold">
              Evidence ledger
            </h2>
            <p className="mt-2 text-sm text-muted-foreground">
              Fetched page text is treated as untrusted data, reduced to
              sanitized evidence, and never executed here.
            </p>
          </div>
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Source</TableHead>
                <TableHead>Category</TableHead>
                <TableHead>Evidence</TableHead>
                <TableHead>Confidence</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {report.evidence.map((item) => (
                <TableRow key={item.id}>
                  <TableCell>
                    <span className="source-badge">{item.source}</span>
                  </TableCell>
                  <TableCell className="font-medium">
                    {item.category.replaceAll('_', ' ')}
                  </TableCell>
                  <TableCell className="min-w-[360px] whitespace-normal">
                    <p className="font-medium">{item.summary}</p>
                    <p className="mt-1 text-xs leading-5 text-muted-foreground">
                      {item.detail}
                    </p>
                  </TableCell>
                  <TableCell>
                    <span className="capitalize">{item.confidence}</span>
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </section>

        <section
          className="rounded-xl bg-ink p-6 text-paper sm:p-8"
          aria-labelledby="next-heading"
        >
          <div className="grid gap-8 lg:grid-cols-[1fr_1.2fr]">
            <div>
              <p className="eyebrow text-signal">Next: behavioral proof</p>
              <h2
                id="next-heading"
                className="mt-3 text-3xl font-semibold tracking-[-.04em]"
              >
                A source scan is the beginning, not the verdict.
              </h2>
              <p className="mt-4 max-w-lg leading-7 text-paper/65">
                Run the identical headset task through an accessible UI and
                structured WebMCP tools, then compare observed state
                transitions.
              </p>
              <Button
                nativeButton={false}
                className="mt-6 bg-signal text-ink hover:bg-signal/85"
                render={<Link href="/lab" />}
              >
                Open the proof lab <ArrowRight data-icon="inline-end" />
              </Button>
            </div>
            <ol className="space-y-3">
              {report.recommendations
                .slice(0, 4)
                .map((recommendation, index) => (
                  <li
                    key={`${recommendation.priority}-${recommendation.title}`}
                    className="flex gap-4 border-t border-paper/15 pt-3"
                  >
                    <span className="font-mono text-xs text-signal">
                      0{index + 1}
                    </span>
                    <div>
                      <p className="font-semibold">{recommendation.title}</p>
                      <p className="mt-1 text-sm leading-6 text-paper/60">
                        {recommendation.detail}
                      </p>
                    </div>
                  </li>
                ))}
            </ol>
          </div>
        </section>

        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-border pt-5 text-xs text-muted-foreground">
          <span>
            {report.response.bytesRead.toLocaleString()} bytes analyzed ·{' '}
            {report.response.redirects} redirect
            {report.response.redirects === 1 ? '' : 's'} · HTTP{' '}
            {report.response.status}
          </span>
          <a
            className="inline-flex items-center gap-1 font-semibold text-foreground"
            href={report.finalUrl}
            target="_blank"
            rel="noreferrer"
          >
            Open scanned page{' '}
            <ExternalLink className="size-3" aria-hidden="true" />
          </a>
        </div>
      </div>
    </main>
  );
}
